#!/usr/bin/env python3
"""Generate one Home Assistant package file per indoor unit.

Takes homeassistant/pioneer_modbus.yaml (written for a single unit called
"Unit 2") and writes a copy per unit with its own name, entity IDs, gateway
host and TCP port. Home Assistant merges the modbus: and template: lists from
all package files, so each unit can live in its own file.

Example:
    python3 tools/make_ha_package.py --host 192.168.1.50 --out build/ \\
        bedroom:Bedroom:23 bathroom:Bathroom:26 living_room:"Living Room":29

Each unit is slug:Display Name:tcp_port. Copy the resulting files to
/config/packages/ in Home Assistant.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TEMPLATE = Path(__file__).resolve().parent.parent / "homeassistant" / "pioneer_modbus.yaml"


def render(template: str, slug: str, name: str, host: str, port: int) -> str:
    if not re.fullmatch(r"[a-z0-9_]+", slug):
        raise ValueError(f"slug must be lowercase letters, digits and underscores: {slug!r}")
    text = template.replace("pioneer_unit_2", f"pioneer_{slug}")
    text = text.replace("Pioneer Unit 2", f"Pioneer {name}")
    text, hosts = re.subn(r"(?m)^(\s*host:\s*)\S+.*$", rf"\g<1>{host}", text, count=1)
    text, ports = re.subn(r"(?m)^(\s*port:\s*)\d+.*$", rf"\g<1>{port}", text, count=1)
    if hosts != 1 or ports != 1:
        raise ValueError("template no longer has exactly one host: and one port: line")
    return f"# Generated by tools/make_ha_package.py for {name} (TCP port {port}).\n" + text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", required=True, help="RS485-to-TCP gateway address")
    ap.add_argument("--out", required=True, help="output directory")
    ap.add_argument("units", nargs="+", help="slug:Display Name:tcp_port")
    args = ap.parse_args()

    template = TEMPLATE.read_text()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for spec in args.units:
        try:
            slug, name, port = spec.split(":")
            path = out / f"pioneer_{slug}.yaml"
            path.write_text(render(template, slug, name, args.host, int(port)))
        except ValueError as err:
            print(f"{spec}: {err}", file=sys.stderr)
            return 1
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
